spring:
    application:
      name: demo

server:
  port: 8080

api:
  exchange-rates:
    key: fb8e32ea24504abe87ede6cb8aeb340f

springdoc:
  packages-to-scan: com.example.demo
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html # http://localhost:8080/swagger-ui/index.html
  use-management-port: false
  show-actuator: true

logging:
  level:
    org:
      springframework:
        security: DEBUG
    web: WARN
    root: INFO
    com.ust.user_service: DEBUG
  pattern: "%msg%n"